In [9]:
import numpy as np

In [10]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [11]:
w1,w2,w3=0.3,0.2,0.5
kanto_temp=73
kanto_rainfall = 67
kanto_humidity = 43

In [13]:
kanto_yield_apples = kanto_temp *w1 + kanto_rainfall * w2 + kanto_humidity *w3
kanto_yield_apples

56.8

In [20]:
kanto_detail=[73,67,43]
weights=[0.3,0.2,0.5]

In [21]:
np.dot(kanto_detail,weights)            # np.dot =  dot product 
#(it maps with each element in same position with diffent list  and multiply them and then sum of all values)

56.8

In [22]:
sum(kanto_detail*weights)

TypeError: can't multiply sequence by non-int of type 'list'

In [25]:
kanto=np.array([73,67,43])
weights=np.array(weights)

In [28]:
sum(kanto*weights)     # sum is defualt python function

56.8

In [30]:
(kanto*weights).sum()   # .sum() this is fumction that written in numpy

56.8

In [60]:
arr1=list(range(10000000))
arr2=list(range(10000000,20000000))

In [70]:
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)
len(arr1_np)
len(arr2_np)

10000000

In [68]:
%%time
np.dot(arr1_np,arr2_np)

Wall time: 13 ms


690258880

In [69]:
%%time
result=0
for i,j in zip(arr1,arr2):
    result+=i*j
result

Wall time: 4.65 s


833333233333335000000

In [77]:
x=np.array([1,'joy',0.5])
x

array(['1', 'joy', '0.5'], dtype='<U32')

In [83]:
%%time
np.shape(arr1_np)

Wall time: 0 ns


(10000000,)

In [80]:
%%time
np.matmul(arr1_np,arr2_np)

Wall time: 35.1 ms


690258880

In [84]:
from urllib import request
request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv',
    'climate.txt',
)

('climate.txt', <http.client.HTTPMessage at 0xcd65d30>)

In [93]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [95]:
climate_data.dtype

dtype('float64')

In [97]:
weights=np.array([0.3,0.2,0.5])

In [102]:
climate_data @ weights

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [103]:
np.matmul(climate_data,weights)

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])